### ISSUE TITLE
Tracks Numbering

### ISSUE THREAD

**Issue by edcartner** [PowerPlatformAF/PowerPlatformAF#29]
Currently, the tracks are numbers 1 - 3, where three is the base for the other two tenants of the platform. In reading the AF, it appears when you present build first, then road map, and finally enterprise management, you're suggesting that that is the order of importance. I would recommend either switching 1 & 3 (so that you start with EM), or removing the numbering entirely. If numbering is removed entirely, it still seems most logical that the PPAF addresses EM prior to the road map and build when addressing the three-pronged approach.

This way, you first present EM which feeds both the road map and build, then you head on to the road map, which feeds into the build. It presents a clearer order of  what makes sense for adoption and increases the apparent importance of enterprise management.

**Comment by edcartner** [comment]
@andrewdwelch any thoughts from your off-line discussions of PPAF on this?

**Comment by andrewdwelch** [comment]
I think I am probably in favor of this. The only drawback is that here we are changing something where there is a ton of existing material out there, so I wonder if it is more trouble than it is worth? Again generally in favor but I can be persuaded otherwise. @manuelap-msft @LeeMBaker @lucyalicebourne @KeithWhatling thoughts? 

Let's queue this up for discussion next time we determine what's going into next edition.

**Comment by edcartner** [comment]
My thought would be just replacing "track 1: build" with "build track." In the PPAF itself, seems like a CTRL+F fix (and perhaps a few graphics), and the rest isn't so impacted as to confuse the meaning of the documentation (i.e., if it doesnt get updated the world won't end). Moving forward, it would just be phasing it out as to promote the equality of the tracks - the same way we woudn't call the Platform the "Third Cloud" because it makes it seem lesser. We promote this feeling of inequality with EM by calling it the "Third Track."

**Comment by andrewdwelch** [comment]
So @manuelap-msft and I were discussing this offline. One thing that occurred to us is that we have to be careful so that we don't end up in a situation where you end up with the end goal becoming governance rather than governance being the means to an end of real value.

So @edcartner based on your above is the idea that we're really just scrapping the numbers of the tracks and calling it a day?

**Comment by edcartner** [comment]
@andrewdwelch  yes.
