### ISSUE TITLE
"Citizen Developers" vs "Pro Developers" vs [Something Else?] needs to be clarified

### ISSUE THREAD

**Issue by andrewdwelch** [PowerPlatformAF/PowerPlatformAF#3]

**Comment by Pieter-Veenstra** [comment]
Hi @andrewdwelch further to last night's discussion. 

How about DIY (do-it-yourself) developer. 

If you look at general DIY building work, a DIY-er does things a pro builder does. However he hasn't had any specific training. When a clever DIY-er hits a problem where he needs a qualified person then he might find a pro builder to do the work.

**Comment by andrewdwelch** [comment]
@Pieter-Veenstra this is a really interesting idea because I think it shifts the focus away from the nature of the person and onto the nature of the work. In a DIY context we're not talking about what the person can or can't do, but instead we're talking about the nature of how they're doing it. Really worth thinking about it.

**Comment by iAmManCat** [comment]
@andrewdwelch I had a few ideas for different sub-classes of the Developer Class.

The way I look at it, whether you've just created your first Hello World, your first VBA snippet, your first batch file or your first PowerApp or Flow, from that point on you're a Developer. We could argue about Junior or Senior or Pro or Citizen all day, but in the end we are all Developers of different skill levels.

For sub-classes of what Development stage you're at with regard to the Power Platform, I had a few ideas, but it's a WIP and I welcome any comments and ideas/changes:

### **{ PowerPlatform Developer Abilities }**

**PowerPlatform Innovator**

- Creates ideas and basic singular PowerApps/Flows/BI's based on those ideas

**PowerPlatform Integrator**

- Creates complex ideas that require integration of multiple Power Platform technologies

**PowerPlatform Imaginator**

- Creates custom components, whether through an in-App component creation or through the PCF

**PowerPlatform Illuminator**

- Shares knowledge of innovative/integrated/imagined solutions with the public, whether through blog/vlog/speaker/interview or other public platform

**PowerPlatform Instrumentalist**

- Lives, breathes and sings the Power Platform, able to use all parts simultaneously to create Enterprise-grade Applications with ease, knowledgeable on and capable of all parts of the Power Platform


I really like the idea of DIY Developer, however I still feel that the 'classic' developers will still find a way to pick that apart and cause more gate-keeping, tension and arguments.

**Comment by KeithWhatling** [comment]
I really like the idea @iAmManCat of the names, and love the marketing with the "I" in each one. Can really see that working as pseudo personas.

**Comment by sksumner** [comment]
Loving the idea of alliteration - We'd need to partner it with a framework of which roles an organisation needs, who does what, how many of each role make a good team to build an x etc. It's useful for an organisation to see what is needed to build a community / team rather than a lone wolf scenario who is the "power platform person".

Are we saying that the roles are split rather than any progressive path - people generally like to add to skills so you may end up with the same hierarchy of which role is better / more progressed as the developer label if we don't provide the guidance as to the value of all roles.

If we looked at other models like DISC profiling that could help with coming up with this type of role guidance - so this is where you analyse the traits in a personality and assign color or letters etc - its not right or wrong to be any one and you can be many with a stronger skills set in any one
Reference material here -  https://www.discprofile.com/what-is-disc/overview/ 

Also just realised that we would be creating I's  now we's - not sure it matters but spotted it while writing :)

**Comment by iAmManCat** [comment]
(in hindsight: sorry for long blurb, autism takes over sometimes!)

Yes! Wow, Those are brilliant points @sksumner - I wasn't thinking particularly of hierarchy and was hoping they would be individual skills that could be mixed and combined (and that we'd break them down into smaller or more unique parts, or other roles that combine certain of the abilities ..and to have a lot more of them). The DISC profiling method would help a lot (I had no idea that was even a thing!)

I came up with the concept of these abilities as _I am the lone wolf 'power platform person'_ currently. I'm trying to grow the internal community but have absolute minimal support from the business except where it comes to _Me_ replacing a business process with the PowerPlatform. I'm in process of drafting a SharePoint site that outlines each of the parts, what they're good for, why we should be moving to them, the benefits of community and business-wide involvement, a Teams group where everyone can ask questions and get instant responses to queries, and some news items to garner more interest.

The problem has been that as I'm 'the only power platform person', I have been stacked with a work backlog 50+ items deep since I started last year (that keeps growing) and have no time to do any promotion and adoption work within the company if I'm to keep producing results with the spoons I have per day! Have only recently managed to convince them to give me 20% of my time to do this..

I was thinking along the lines of individual skill-sets, where someone may have one or more of them - I was also thinking there would be more roles, these are just the ones I've come up with so far. If we remove the Instrumentalist role altogether and add more 'specialist skill-sets/combinations', we take out the tiers problem, as there wouldn't be a 'peak' role that is higher than all of the rest. They'd all be good, just different.

> framework of which roles an organisation needs, who does what, how many of each role make a good team to build an x etc.

Yes, this would be super-useful and could further empower the idea that not everyone has the same skill-set so you could use a combination of Individuals to gain the overall skill-set needed for that Team. I was initially thinking something like:

> I am a PowerPlatform innovator, integrator and Illuminator, working on gaining knowledge on the PCF Imaginator skills, and We are the PowerPlatform Solution Team at XYZ specialising in the modernisation of detailed and complex business process. Our Unique Creations team consisting of _A_, a particularly passionate illuminator & Innovator, and _B_, a highly-skilled Imaginator are focused on improving processes within the company's HR stream currently. Our Alternate Solutions Team, consisting of _C_,_D_,_E_,_F_ and _G_ who all have varying PowerPlatform skills are focused on replacing standard business processes and determining newer and better ways for us to do business.


..And yes, lots of I's in there as the skills are referencing that **Individual's** ability, as we are all definitely Individuals with vastly different abilities, skill-sets, and ways of approaching problems/solutions.
I see it as Everyone is an Individual, and many Individuals make a Team thrive.. or "Any more than one I becomes a Team"  ...I'm not great at taglines, so that's all I've got for now.

**Comment by SamGr09** [comment]
@iAmManCat can certainly relate to the lone wolf scenario and a backlog a mile long. So I am also creating a community of practice "O365 Power Users Community". At the moment like @LuiseFreese we are referring to our Power Users as Collaborators for collaboration tools or Makers for the Powerplatform tools. We just crossed over from pilot phase of 8 members to launching an intake of 15-20. 🤞

Lack of sanctioned support has been an issue. But with the support of my team leader we have built the community of practice on teams with a SharePoint Portal.

So far our early pilot users are excited and its great to see their faces during all those wow moments.

**Comment by andrewdwelch** [comment]
I am blown away by the degree of thought that our community is putting into this topic at the moment. It sounds to me as there are several strings we should be pulling here:

**1) What do we call people who "make things" on Power Platform, regardless of your skill level?** At the London User Group someone -- I think it was @Pieter-Veenstra -- suggested simply "Power Platform Developer" (could have been "PowerApps Developer", but I do think we need to start thinking holistically about the platform. @LuiseFreese has suggested "Maker".

**2) Are there different levels of skill to this person**, i.e. is there a continuum of skill that takes someone from what we today call "citizen developer" to what today we call "professional developer"? There is an interesting discussion on this idea forming at [https://github.com/PowerPlatformAF/PowerPlatformAF/issues/18](https://github.com/PowerPlatformAF/PowerPlatformAF/issues/18).

One thing occurs to me that in the traditional "developer" or "engineer" world, nobody ever knew everything. Folks gained proficiency in one of many disciplines / languages / techniques / etc. I feel that flexibility needs to be adapted to suit this new toolset, as well.

**Comment by andrewdwelch** [comment]
So at Power Platform Saturday Sweden, Scott Durow and Sara Lagerquist are suggesting the idea of the “Functional Developer” that doesn’t come from a software engineering background but who work pretty much up and down the Power Platform stack. Seeding the idea here for further discussion.

**Comment by LuiseFreese** [comment]
It matches nicely with the functional consultant 😎

**Comment by Pieter-Veenstra** [comment]
> 1) What do we call people who "make things" on Power Platform, regardless of your skill level? At the London User Group someone -- I think it was @Pieter-Veenstra -- suggested simply "Power Platform Developer" (could have been "PowerApps Developer", but I do think we need to start thinking holistically about the platform. @LuiseFreese has suggested "Maker".

In my opinion there is no need to box people, projects or work is categorised. Personally I do both code and no/low code. Whatever is most suitable for the project. I do however have a preference for no/low code. I have this preference not because of my skills. The preference of low code is simply a matter of what is easier to receive/maintain by my clients.

**Comment by frederikbroux** [comment]
Personally I don't really like the terms DIY-developer and citizen developer. It sounds a bit like they create inferior things compared to the Pro developer. Maker sounds a lot better. I don't like Pro-developer as well since that sounds like bragging to other developers.

My suggestion would be that we use Power-developer for the people that create solutions with the help of powertools like PowerApps and PowerBI. I would use Code-developer for the ones that use code to create solutions with code.

**Comment by andrewdwelch** [comment]
Hey everyone, thanks for your input and thoughts on this one! We've made some updates to the framework and created a new section called "Shared Developer Community". There we've recommended a model for "Citizen Developers" and "Power Platform Developers", and we've suggested against ever using the term "Pro Developers". The idea here based on all the feedback was to preserve the "Citizen Developer" phrase which we think is here to stay, but come up with a way of describing both Citizen Developers and those who do this work "full time".

https://github.com/PowerPlatformAF/PowerPlatformAF/wiki/4-Nurturing-the-Community#shared-developer-community

Always evolving, but here we are for now. Closing this item 🙂
